language: node_js
node_js:
  - '10'
  - '8'

branches:
  only:
  - master
install:
- npm install
script:
- npm run test
after_success:
- './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'

notifications:
  email: false